DotNetMVCBaseProject/Models/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DotNetMVCBaseProject.Models
{
    public class Account
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string Password { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public DateTime BirthDay { get; set; }
        public bool Gender { get; set; }
        public Common.Enums.AccountRole Role { get; set; }
    }
}

DotNetMVCBaseProject/Controllers/AccountController.cs
using DotNetMVCBaseProject.DAO;
using DotNetMVCBaseProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DotNetMVCBaseProject.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult ViewLogin(string message)
        {
            //If there has been already an account saved in cookie => skip login
            if (CheckCookie())
            {
                return RedirectToAction("Index", "Home");
            }
            //Else show login page
            if (message != null)
                ViewBag.Message = message;
            else
                ViewBag.Message = "";
            return View();
        }
        public ActionResult CheckLogin(string username, string password)
        {
            ClearCookieAndSession();

            //Validate login
            AccountDAO accountDAO = new AccountDAO();
            Account account = accountDAO.GetOne(username, password);
            if (account != null)
            {// login successful
                //Save into cookie
                FormsAuthentication.SetAuthCookie(username, false);

                //Save account into session
                if (Session["CurrentAccount"] == null)
                {
                    Session.Add("CurrentAccount", account);
                }
                else
                {
                    Session["CurrentAccount"] = account;
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {// login failed => reload                
                return RedirectToAction("ViewLogin", "Account", new { message = "Invalid Username or Password" });
            }
        }
        public ActionResult ViewRegister(string message)
        {
            //If there has been already an account saved in cookie => skip login
            if (CheckCookie())
            {
                return RedirectToAction("Index", "Home");
            }
            //Else show login page
            if (message != null)
                ViewBag.Message = message;
            else
                ViewBag.Message = "";
            return View();
        }
        public ActionResult CheckRegister(Account newAccount)
        {
            ClearCookieAndSession();

            //Validate register
            AccountDAO accountDAO = new AccountDAO();
            newAccount.Role = Common.Enums.AccountRole.User;
            int result = accountDAO.Insert(newAccount);

            if (result == 1)
            {// register successful
                //Save into cookie
                FormsAuthentication.SetAuthCookie(newAccount.Username, false);

                //Save account into session
                if (Session["CurrentAccount"] == null)
                {
                    Session.Add("CurrentAccount", newAccount);
                }
                else
                {
                    Session["CurrentAccount"] = newAccount;
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {// register failed => reload                
                return RedirectToAction("ViewRegister", "Account", new { message = "Account has already existed" });
            }
        }
        public ActionResult Logout()
        {
            ClearCookieAndSession();
            return RedirectToAction("ViewLogin", "Account");
        }
        private bool CheckCookie()
        {
            //TODO:
            //  Return true if there is a valid account being saved in cookie
            //  Return false if otherwise
            AccountDAO accountDAO = new AccountDAO();
            {
                Account savedAccount = null;
                if (FormsAuthentication.CookiesSupported == true)
                {
                    if (Request.Cookies[FormsAuthentication.FormsCookieName] != null)
                    {
                        try
                        {
                            string username = FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name;
                            savedAccount = accountDAO.GetOne(username);
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine("Error in Global.asax.cs,  FormsAuthentication_OnAuthenticate(): " + ex.Message);
                            throw ex;

                        }
                    }
                }
                if (savedAccount != null)
                {
                    //Save account into session
                    if (Session["CurrentAccount"] == null)
                    {
                        Session.Add("CurrentAccount", savedAccount);
                    }
                    else
                    {
                        Session["CurrentAccount"] = savedAccount;
                    }
                    return true;
                }
                return false ;
            }
        }
        private void ClearCookieAndSession()
        {
            //Clear cookie
            FormsAuthentication.SetAuthCookie(String.Empty, false);

            //Clear session
            if (Session["CurrentAccount"] != null)
            {
                Session["CurrentAccount"] = null;
            };
        }
        
    }
}

DotNetMVCBaseProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMVCBaseProject.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }


    }
}

DotNetMVCBaseProject/Controllers/SystemInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMVCBaseProject.Controllers
{
    public class SystemInfoController : Controller
    {
        // GET: SystemInfo
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

DotNetMVCBaseProject/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DotNetMVCBaseProject.Controllers
{
    public class UserInfoController : Controller
    {
        // GET: UserInfo
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
    }
}

DotNetMVCBaseProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

DotNetMVCBaseProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Admin", "Index", "SystemInfo")</li>
                    <li>@Html.ActionLink("User", "Index", "UserInfo")</li>
                    @if (Session["CurrentAccount"] == null)
                    {
                        <li>@Html.ActionLink("Login", "ViewLogin", "Account")</li>
                        <li>@Html.ActionLink("Register", "ViewRegister", "Account")</li>
                    }
                    else
                    { 
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DotNetMVCBaseProject/Views/SystemInfo/Index.cshtml
@{
    ViewBag.Title = "System Information";
}

<h2>System Information</h2>

DotNetMVCBaseProject/Views/UserInfo/Index.cshtml
@{
    ViewBag.Title = "User Information";
}

<h2>User Information</h2>